# Overrides for the production environment.
logLevel: warn
regions:
  cn:
    apiBaseUrl: https://rag-server-svc-plus-266500572462.asia-northeast1.run.app
    authUrl: https://accounts-svc-plus-266500572462.asia-northeast1.run.app
    dashboardUrl: https://console.svc.plus
    internalApiBaseUrl: https://rag-server-svc-plus-266500572462.asia-northeast1.run.app
  global:
    apiBaseUrl: https://rag-server-svc-plus-266500572462.asia-northeast1.run.app
    authUrl: https://accounts-svc-plus-266500572462.asia-northeast1.run.app
    dashboardUrl: https://console.svc.plus
    internalApiBaseUrl: https://rag-server-svc-plus-266500572462.asia-northeast1.run.app
