# Overrides for the production environment.
logLevel: warn
regions:
  cn:
    apiBaseUrl: https://cn-api.svc.plus
    authUrl: https://accounts.svc.plus
    dashboardUrl: https://console.svc.plus
  global:
    apiBaseUrl: https://global-api.svc.plus
    authUrl: https://accounts.svc.plus
    dashboardUrl: https://console.svc.plus
